# Generated by Django 4.2.7 on 2025-10-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('tailored_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Tailored Resume',
                'verbose_name_plural': 'Tailored Resumes',
                'ordering': ['-created_at'],
            },
        ),
    ]
