# Generated by Django 4.2.7 on 2025-10-17 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_cv_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
