# Generated by Django 4.2.7 on 2025-10-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_tailoredresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecv',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Extracted and potentially user-corrected text content', null=True),
        ),
    ]
